allowBuilds:
  '@apollo/protobufjs': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  protobufjs: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
overrides:
  fastify: 5.8.5
