apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: analytics-pod-kill
  namespace: analytics
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: [analytics]
    labelSelectors:
      app.kubernetes.io/name: analytics-service
  duration: 30s
  scheduler:
    cron: "@every 30m"
